### ISSUE TITLE
The results for MS (monocular + stereo supervision) on KITTI

### ISSUE THREAD

**Issue by xuanlongORZ** [jhornauer/GrUMoDepth#2]
Thank you for sharing the codes. BTW the paper is clear and intuitive.

However, I did not find the results for MS (monocular + stereo supervision) on KITTI dataset in the paper, while in mono-uncertainty paper, the authors provided them. I know this is an additional request, but since usually MS has better depth accuracy than M and S, maybe you can provide its uncertainty results in the supplementary material?

Thank you.

**Comment by jhornauer** [comment]
Thank you for the interest in our paper. Unfortunately, due to time constraints, we cannot include any more experiments in our paper at this time.
