### ISSUE TITLE
Python file evaluate_supervised.py

### ISSUE THREAD

**Issue by ZakariaeMachkour** [jhornauer/GrUMoDepth#3]
Thank you for sharing the codes and the models. 
While reading the code I have a remark regarding the python file [**evaluate_supervised.py**.](https://github.com/jhornauer/GrUMoDepth/blob/main/evaluate_supervised.py) Is there a specific reason you are testing separately **if opt.grad** in lines [**204**](https://github.com/jhornauer/GrUMoDepth/blob/4229c509069eb053d7e0908a68eb9f6ed8b4e6d8/evaluate_supervised.py#L204) and [**217**?](https://github.com/jhornauer/GrUMoDepth/blob/4229c509069eb053d7e0908a68eb9f6ed8b4e6d8/evaluate_supervised.py#L217) 
Thanks.

**Comment by jhornauer** [comment]
There is no specific reason, you could also combine the two if statements.
