### ISSUE TITLE
Problems in installing requirements from .yml file 

### ISSUE THREAD

**Issue by shub2612** [jhornauer/GrUMoDepth#4]
Dear Authors, @jhornauer
Thank you for the insightful paper. I was trying to implement this on a different dataset. In the process of creating a virtual Conda env, when I am trying to install packages from the .yml file around 50% are saying no version available.
Do you know what the reason could be for this? 

Thank you,
Shubham

**Comment by jhornauer** [comment]
Hi Shubham, 

I have rechecked the creation of the conda env from the .yml file. I could not find any problems. Unfortunately, I do not know why the installation of the packages fails in your case.

**Comment by shub2612** [comment]
Hi, @jhornauer 
Thank you. The issue was related to the channels present in my .condarc file. It got resolved yesterday once I changed them. 

I had another question, more of a doubt in my understanding related to What AURG is and what it signifies. I would rather close this issue and open a new one with the title AURG so that someone else who is facing the same can reach it quickly.

Thank you,
