### ISSUE TITLE
Doubts in AURG values

### ISSUE THREAD

**Issue by shub2612** [jhornauer/GrUMoDepth#5]
Hi @jhornauer 

I had doubts in my understanding regrading what AURG means and what it signifies.

First the paper says that AURG is an estimation if we assume there is no modelling in the system. Here no modelling means, not arranging the uncertainty values in descending order or something else? what does it mean intuitively when we say that higher the value of AURG the better?

Thank you for your time,
Shubham

**Comment by jhornauer** [comment]
Hi Shubham, 

to calculate the AURG, the area under the difference between the actual sparsification curve and the random sparsification curve is calculated. To obtain the actual sparsification curve, the pixels are arranged in descending order according to the uncertainty. Then, the pixels with the highest uncertainty are removed and the corresponding depth estimation metric is calculated for the remaining pixels. It is expected that the depth estimation metric will improve when the pixels with the highest uncertainty are removed. For random sparsification, the depth estimation metric is not expected to improve when the pixels with the highest uncertainty are removed. Therefore, the depth estimation metric remains constant when pixels are removed. A high AURG value means that the uncertainty estimate is better than a random estimate of uncertainty and therefore is better than not modeling the uncertainty at all.

**Comment by shub2612** [comment]
Hello @jhornauer ,

Thank you for a detailed explanation on the topic and my apologies for replying late. 
I tried to understand the explanation and I am writing what I understood. Can you please point out flaws in it if any. And thank you so much in advance!!

There is pred_depth, gt_depth and estimated uncertainty per pixel.  For calculating the **actual sparsification curve**, arrange pixels in decreasing order of estimated uncertainty. For these pixels then calculate the error, depending on the metric (abs_rel, RMSE, a1). Then start removing pixels in fractions and correspondingly plot the graph. The y axis :- error and x axis :- fractions of pixels removed.

For Random sparsification curve:- Pixels are not arranged in descending order. Error is calculated for all the pixels, then the fraction of pixels are removed randomly thus the error is expected to remain nearly constant and not continuously decrease.

For oracle sparsification curve:- Calculate the error as per the metric and then the pixels are arranged in descending order. Then remove the fraction of pixels and calculate the error for the remaining ones.

AUSE:- Area under the difference of Actual sparsification curve and Oracle sparsification curve. The lesser the better.
AURG:- Area under the difference of Actual sparsification curve and Random sparsification curve. The higher the better.

This explanation is my understanding of the concept and I would be really glad if you could point out the flaws in it.

Thank you so much!!

**Comment by jhornauer** [comment]
Hi Shubham, 

you have understood the explanation correctly.

**Comment by shub2612** [comment]
Hi @jhornauer Thank you so much!!
