### ISSUE TITLE
Problem with generate_maps.py

### ISSUE THREAD

**Issue by shub2612** [jhornauer/GrUMoDepth#6]
Hi @jhornauer 
I am facing an issue when running the generate_maps.py 
In line 487, when calling the get_mono_ratio function we are trying to resize the reciprocal of pred_disps to the gt_depths. But the cv2.resize function as defined is not working and throwing an error saying : **IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed**

In my opinion I found this to be the case because the resize parameters as defined in the function (get_mono_ratio) are not giving the right image dimensions.

Can you please help with the issue.

Thank you,
Shubham

**Comment by jhornauer** [comment]
Hi Shubham, 

what setup are you trying to run? What parameters do you choose when you run the script? And which version of cv2 do you have installed?

**Comment by shub2612** [comment]
Hello @jhornauer ,
Apologies for a late response. I went through the issue and found that the gt_depth.npz file that I was referring to was incorrect. Because of this the resize function was throwing an index error. The issue is resolved.

Thank you
